# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
  - name: environment
    type: string
    values:
      - dev
      - stage
    default: dev

variables:
  terraform_state_rg: 'terraform-state-rg'
  tfstate: 'tfstate'

stages:
- stage: plan_destroy
  jobs:
    - job: plan_destroy
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/end-to-end-project/all-code/${{ parameters.environment }}'
            backendServiceArm: 'Azure subscription 1(1)(945a5939-f994-4cc8-9fbb-65f8e87eaf5a)'
            backendAzureRmResourceGroupName: '$(terraform_state_rg)'
            backendAzureRmStorageAccountName: 'tf${{ parameters.environment }}afrah001'
            backendAzureRmContainerName: '$(tfstate)'
            backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/end-to-end-project/all-code/${{ parameters.environment }}'
            environmentServiceNameAzureRM: 'Azure subscription 1(1)(945a5939-f994-4cc8-9fbb-65f8e87eaf5a)'
            environmentAzureRmUseIdTokenGeneration: true
            commandOptions: '-destroy'
          env:
            TF_VAR_ssh_public_key: $(sshPublicKey)

- stage: destroy_env
  jobs:
    - deployment: destroy
      pool:
        vmImage: ubuntu-latest
      environment: 'terraform-destroy-${{ parameters.environment }}'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: TerraformInstaller@1
                inputs:
                  terraformVersion: 'latest'
              - task: TerraformTask@5
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/end-to-end-project/all-code/${{ parameters.environment }}'
                  backendServiceArm: 'Azure subscription 1(1)(945a5939-f994-4cc8-9fbb-65f8e87eaf5a)'
                  backendAzureRmResourceGroupName: '$(terraform_state_rg)'
                  backendAzureRmStorageAccountName: 'tf${{ parameters.environment }}afrah001'
                  backendAzureRmContainerName: '$(tfstate)'
                  backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'
              - task: TerraformTask@5
                inputs:
                  provider: 'azurerm'
                  command: 'destroy'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/end-to-end-project/all-code/${{ parameters.environment }}'
                  commandOptions: '--auto-approve'
                  environmentServiceNameAzureRM: 'Azure subscription 1(1)(945a5939-f994-4cc8-9fbb-65f8e87eaf5a)'
                  environmentAzureRmUseIdTokenGeneration: true
                env:
                  TF_VAR_ssh_public_key: $(sshPublicKey)
