rgname                 = "dev-afrah-rg"
service_principal_name = "dev-afrah-spn"
keyvault_name          = "dev-afrah-kv-101"
SUB_ID = "945a5939-f994-4cc8-9fbb-65f8e87eaf5a"
cluster_name = "dev-afrah-cluster"
node_pool_name = "devnp"
